flow_control:
  train_model: True
  test_model: True
  write_log: True

train_params:
  n_without_improvements: 4
  early_stopping: True
  save_best: False
  save_last: False
  train_type: "forms"
  model_name: "BaselineTagger"
  batch_size: 128
  n_epochs: 5
  grad_clip: 3.
  lr: 1e-03

model_params:
  hidden_size: 512
  emb_dim: 512
