
flow_control:
  train_model: True
  test_model: True
  write_results: False
  initialize_tokenizers: False

train_params:
  n_without_improvements: 4
  early_stopping: True
  save_best: True
  save_last: False
  train_type: "lemmas"
  model_name: "CnnCrfTagger"
  batch_size: 128
  n_epochs: 5
  grad_clip: 3.
  lr: 1e-03

model_params:
  emb_dim: 512
  hidden_size: 1024
  convolution_layers: 8
  kernel_size: 3
  spatial_dropout: 0.3