flow_control:
  train_model: True
  test_model: True
  write_log: True

train_params:
  n_without_improvements: 4
  early_stopping: True
  save_best: True
  save_last: False
  train_type: "forms_shuffled"
  model_name: "LstmTagger"
  batch_size: 128
  n_epochs: 1
  grad_clip: 3.
  lr: 1e-03

model_params:
  lstm_layers: 3
  layer_dropout: 0.3
  bidirectional: True
  hidden_size: 512
  emb_dim: 512
  spatial_dropout: 0.3