
flow_control:
  train_model: False
  test_model: True
  write_results: False
  write_log: True

train_params:
  n_without_improvements: 4
  early_stopping: True
  save_best: False
  save_last: False
  train_type: "lemmas"
  model_name: "RandomTagger"
  batch_size: 128
  n_epochs: 1
  grad_clip: 3.
  lr: 1e-03
  seed: 1
