flow_control:
  train_model: True
  test_model: True
  write_log: True

train_params:
  n_without_improvements: 10
  early_stopping: True
  save_best: True
  save_last: False
  train_type: "forms"
  model_name: "TransformerCrfTagger"
  batch_size: 256
  n_epochs: 100
  grad_clip: 3.
  lr: 1e-04

model_params:
  hidden_size: 2048
  emb_dim: 1024
  dropout: 0.1
  n_heads: 8
  num_layers: 8
