
flow_control:
  train_model: True
  test_model: True
  write_results: False

train_params:
  n_without_improvements: 4
  early_stopping: True
  save_best: True
  save_last: True
  train_type: "lemmas"
  model_name: "TransformerTagger"
  batch_size: 128
  n_epochs: 1
  grad_clip: 3.
  lr: 1e-05

model_params:
  hidden_size: 512
  emb_dim: 512
  dropout: 0.1
  n_heads: 8
  num_layers: 8
