flow_control:
  train_model: True
  test_model: True
  write_log: True

train_params:
  n_without_improvements: 4
  early_stopping: True
  save_best: True
  save_last: False
  train_type: "lemmas"
  model_name: "TransformerCrfTagger"
  batch_size: 128
  n_epochs: 20
  grad_clip: 3.
  lr: 1e-04

model_params:
  hidden_size: 1024
  emb_dim: 512
  dropout: 0.1
  n_heads: 8
  num_layers: 8
